[project]
name = "inctxt"
version = "0.0.1"
authors = [
  { name = "Akash Gupta", email = "guptaalgebra@gmail.com" },
  { name = "Ivaxi Sheth" },
  { name = "Vyas Raina" },
  { name = "Tanush Chopra" },
  { name = "Michael Li" },
]
requires-python = ">=3.12,<3.13"
dependencies = [
  "torch",
  "transformers",
  "datasets",
  "evaluate", # rouge metric
  "mypy",
  "python-dotenv",
  "rouge_score",
  "joblib",
  "seaborn",
  "openai",
  "transformer-lens>=2.15.4",
]
